services:
  django_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI

  queue:
    build: .
    command: python consumer.py
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
