# Generated by Django 5.1.6 on 2025-03-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_borrowed_by_book_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='due_date',
            new_name='return_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='api.user'),
        ),
    ]
